### using lambda

# Step #1: Clone Benchmark Repository
git clone https://github.com/lambdal/lambda-tensorflow-benchmark.git --recursive
# Step #2: Run Benchmark
# Input a proper gpu_index (default 0) and num_iterations (default 10)
cd lambda-tensorflow-benchmark
./benchmark.sh gpu_index num_iterations
# Step #3: Report Results
# Check the repo directory for folder <cpu>-<gpu>.logs (generated by benchmark.sh)
# Use the same num_iterations in benchmarking and reporting.
./report.sh <cpu>-<gpu>.logs num_iterations

### using tensorflow

pip install tensorflow
git clone https://github.com/tensorflow/benchmarks.git
cd benchmarks/scripts/tf_cnn_benchmarks/

python tf_cnn_benchmark.py --help

python tf_cnn_benchmark.py --model=vgg19 --data_format=NHWC

# To undergo only forward run with batch size 32 and number of batches 100, use the following command:
python tf_cnn_benchmark.py --model=vgg19 --data_format=NHWC --num_gpus=1
--forward_only --batch_size=32 --nun_batches=100
